-- =====================================================
-- LIGHT RHYTHM MANAGEMENT SYSTEM
-- Supabase PostgreSQL Schema Specification
-- Compliant with SRS.md (FR-01 to FR-06, NFR-01 to NFR-06)
-- =====================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. USERS TABLE (FR-04, NFR-02, NFR-06)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. SCHEDULES TABLE (FR-01, FR-04)
CREATE TABLE IF NOT EXISTS public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    period VARCHAR(20) NOT NULL CHECK (period IN ('Morning', 'Day', 'Night')),
    start_time VARCHAR(5) NOT NULL CHECK (start_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
    end_time VARCHAR(5) NOT NULL CHECK (end_time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
    brightness_pct INTEGER NOT NULL CHECK (brightness_pct >= 0 AND brightness_pct <= 100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. ROUTINES TABLE (FR-03, FR-04)
CREATE TABLE IF NOT EXISTS public.routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    period VARCHAR(20) NOT NULL CHECK (period IN ('Morning', 'Day', 'Night')),
    time VARCHAR(5) NOT NULL CHECK (time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
    brightness_pct INTEGER NOT NULL CHECK (brightness_pct >= 0 AND brightness_pct <= 100),
    description TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. ACTIVITY HISTORY AUDIT LOG (FR-06, FR-04)
CREATE TABLE IF NOT EXISTS public.activity_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('LIGHT', 'USER', 'SCHEDULE', 'ROUTINE')),
    title VARCHAR(200) NOT NULL,
    details TEXT NOT NULL DEFAULT '',
    brightness_pct INTEGER CHECK (brightness_pct IS NULL OR (brightness_pct >= 0 AND brightness_pct <= 100)),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. SYSTEM SETTINGS TABLE (FR-04)
CREATE TABLE IF NOT EXISTS public.system_settings (
    key VARCHAR(50) PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_schedules_period ON public.schedules (period);
CREATE INDEX IF NOT EXISTS idx_schedules_start_time ON public.schedules (start_time ASC);
CREATE INDEX IF NOT EXISTS idx_routines_period ON public.routines (period);
CREATE INDEX IF NOT EXISTS idx_routines_time ON public.routines (time ASC);
CREATE INDEX IF NOT EXISTS idx_activity_history_type ON public.activity_history (event_type);
CREATE INDEX IF NOT EXISTS idx_activity_history_timestamp ON public.activity_history (timestamp DESC);

-- 8. AUTO-UPDATE UPDATED_AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION public.trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for schedules
DROP TRIGGER IF EXISTS set_schedules_updated_at ON public.schedules;
CREATE TRIGGER set_schedules_updated_at
BEFORE UPDATE ON public.schedules
FOR EACH ROW
EXECUTE FUNCTION public.trigger_set_timestamp();

-- Trigger for routines
DROP TRIGGER IF EXISTS set_routines_updated_at ON public.routines;
CREATE TRIGGER set_routines_updated_at
BEFORE UPDATE ON public.routines
FOR EACH ROW
EXECUTE FUNCTION public.trigger_set_timestamp();

-- Trigger for system_settings
DROP TRIGGER IF EXISTS set_settings_updated_at ON public.system_settings;
CREATE TRIGGER set_settings_updated_at
BEFORE UPDATE ON public.system_settings
FOR EACH ROW
EXECUTE FUNCTION public.trigger_set_timestamp();

-- 9. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Allow full access for anon, authenticated, and service_role
DROP POLICY IF EXISTS "Allow full access on schedules" ON public.schedules;
CREATE POLICY "Allow full access on schedules" ON public.schedules
    FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access on routines" ON public.routines;
CREATE POLICY "Allow full access on routines" ON public.routines
    FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access on activity_history" ON public.activity_history;
CREATE POLICY "Allow full access on activity_history" ON public.activity_history
    FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access on system_settings" ON public.system_settings;
CREATE POLICY "Allow full access on system_settings" ON public.system_settings
    FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow full access on users" ON public.users;
CREATE POLICY "Allow full access on users" ON public.users
    FOR ALL TO anon, authenticated, service_role USING (true) WITH CHECK (true);
